# Copyright (C) 2023 Roberto Rossini <roberros@uio.no>
# SPDX-License-Identifier: MIT

[project]
name = "2022-mcf10a-cancer-progression"
license = { text = "MIT License" }

[tool.pycodestyle]
ignore = "E226,E302,E41"
max_line_length = 120


[tool.black]
line-length = 120
target-version = ["py310"]

[tool.isort]
profile = "black"

