# Copyright (c) 2023 Roberto Rossini (roberros@uio.no)
# SPDX-License-Identifier: MIT

name: Build diffDomain Dockerfile

on:
  push:
    branches: [ main ]
    paths:
      - ".github/workflows/build-diffdomain*dockerfile.yml"
      - ".github/workflows/build-dockerfile.yml"
      - "containers/diffdomain*.Dockerfile"
      - "containers/assets/robomics-diffdomain*.tar.xz"
  pull_request:
    branches: [ main ]
    paths:
      - ".github/workflows/build-diffdomain*dockerfile.yml"
      - ".github/workflows/build-dockerfile.yml"
      - "containers/diffdomain*.Dockerfile"
      - "containers/assets/robomics-diffdomain*.tar.xz"

jobs:
  build-diffdomain-dockerfile:
    name: Build diffDomain Dockerfile
    uses: paulsengroup/2022-mcf10a-cancer-progression/.github/workflows/build-dockerfile.yml@main
    with:
      dockerfile-glob: "containers/diffdomain*.Dockerfile"

    permissions:
      contents: read
      packages: write
