# Copyright (c) 2023 Roberto Rossini (roberros@uio.no)
# SPDX-License-Identifier: MIT

name: Build clusterProfiler Dockerfile

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/build-cluster-profiler*dockerfile.yml"
      - ".github/workflows/build-dockerfile.yml"
      - "containers/cluster-profiler*.Dockerfile"
  pull_request:
    branches: [main]
    paths:
      - ".github/workflows/build-cluster-profiler*dockerfile.yml"
      - ".github/workflows/build-dockerfile.yml"
      - "containers/cluster-profiler*.Dockerfile"

jobs:
  build-hicrep-dockerfile:
    name: Build clusterProfiler Dockerfile
    uses: paulsengroup/2022-mcf10a-cancer-progression/.github/workflows/build-dockerfile.yml@main
    with:
      dockerfile-glob: "containers/cluster-profiler*.Dockerfile"

    permissions:
      contents: read
      packages: write
