# Copyright (c) 2023 Roberto Rossini (roberros@uio.no)
# SPDX-License-Identifier: MIT

name: Build pyutils Dockerfile

on:
  push:
    branches: [ main ]
    paths:
      - ".github/workflows/build-pyutils*dockerfile.yml"
      - ".github/workflows/build-dockerfile.yml"
      - "containers/pyutils*.Dockerfile"
  pull_request:
    branches: [ main ]
    paths:
      - ".github/workflows/build-pyutils*dockerfile.yml"
      - ".github/workflows/build-dockerfile.yml"
      - "containers/pyutils*.Dockerfile"

jobs:
  build-pyutils-dockerfile:
    name: Build plotting Dockerfile
    uses: paulsengroup/2022-mcf10a-cancer-progression/.github/workflows/build-dockerfile.yml@main
    with:
      dockerfile-glob: "containers/pyutils*.Dockerfile"

    permissions:
      contents: read
      packages: write
