# Copyright (c) 2023 Roberto Rossini (roberros@uio.no)
# SPDX-License-Identifier: MIT

name: Build MaxHiC Dockerfile

on:
  push:
    branches: [ main ]
    paths:
      - ".github/workflows/build-maxhic*dockerfile.yml"
      - ".github/workflows/build-dockerfile.yml"
      - "containers/maxhic*.Dockerfile"
      - "containers/assets/maxhic*.tar.xz"
  pull_request:
    branches: [ main ]
    paths:
      - ".github/workflows/build-maxhic*dockerfile.yml"
      - ".github/workflows/build-dockerfile.yml"
      - "containers/maxhic*.Dockerfile"
      - "containers/assets/maxhic*.tar.xz"

jobs:
  build-maxhic-dockerfile:
    name: Build MaxHiC Dockerfile
    uses: paulsengroup/2022-mcf10a-cancer-progression/.github/workflows/build-dockerfile.yml@main
    with:
      dockerfile-glob: "containers/maxhic*.Dockerfile"

    permissions:
      contents: read
      packages: write
