# Copyright (c) 2023 Roberto Rossini (roberros@uio.no)
# SPDX-License-Identifier: MIT

name: Build samtools Dockerfile

on:
  push:
    branches: [ main ]
    paths:
      - ".github/workflows/build-samtools*dockerfile.yml"
      - ".github/workflows/build-dockerfile.yml"
      - "containers/samtools*.Dockerfile"
  pull_request:
    branches: [ main ]
    paths:
      - ".github/workflows/build-samtools*dockerfile.yml"
      - ".github/workflows/build-dockerfile.yml"
      - "containers/samtools*.Dockerfile"

jobs:
  build-samtools-dockerfile:
    name: Build samtools Dockerfile
    uses: paulsengroup/2022-mcf10a-cancer-progression/.github/workflows/build-dockerfile.yml@main
    with:
      dockerfile-glob: "containers/samtools*.Dockerfile"

    permissions:
      contents: read
      packages: write
