# Copyright (c) 2023 Roberto Rossini (roberros@uio.no)
# SPDX-License-Identifier: MIT

name: Build hic-balancing Dockerfile

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/build-hic-balancing*dockerfile.yml"
      - ".github/workflows/build-dockerfile.yml"
      - "containers/hic-balancing*.Dockerfile"
      - "containers/assets/hic2cool-ng*.tar.xz"
      - "containers/patches/cooler.patch"
  pull_request:
    branches: [main]
    paths:
      - ".github/workflows/build-hic-balancing*dockerfile.yml"
      - ".github/workflows/build-dockerfile.yml"
      - "containers/hic-balancing*.Dockerfile"
      - "containers/assets/hic2cool-ng*.tar.xz"
      - "containers/patches/cooler.patch"

jobs:
  build-hic-balancing-dockerfile:
    name: Build hic-balancing Dockerfile
    uses: paulsengroup/2022-mcf10a-cancer-progression/.github/workflows/build-dockerfile.yml@main
    with:
      dockerfile-glob: "containers/hic-balancing*.Dockerfile"

    permissions:
      contents: read
      packages: write
