# Copyright (c) 2023 Roberto Rossini (roberros@uio.no)
# SPDX-License-Identifier: MIT

name: Build HiCExplorer Dockerfile

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/build-hicexplorer*dockerfile.yml"
      - ".github/workflows/build-dockerfile.yml"
      - "containers/hicexplorer*.Dockerfile"
  pull_request:
    branches: [main]
    paths:
      - ".github/workflows/build-hicexplorer*dockerfile.yml"
      - ".github/workflows/build-dockerfile.yml"
      - "containers/hicexplorer*.Dockerfile"

jobs:
  build-hicexplorer-dockerfile:
    name: Build HiCExplorer Dockerfile
    uses: paulsengroup/2022-mcf10a-cancer-progression/.github/workflows/build-dockerfile.yml@main
    with:
      dockerfile-glob: "containers/hicexplorer*.Dockerfile"

    permissions:
      contents: read
      packages: write
