# Copyright (c) 2023 Roberto Rossini (roberros@uio.no)
# SPDX-License-Identifier: MIT

name: Build HiNT Dockerfile

on:
  push:
    branches: [ main ]
    paths:
      - ".github/workflows/build-hint*dockerfile.yml"
      - ".github/workflows/build-dockerfile.yml"
      - "containers/hint*.Dockerfile"
      - "containers/patches/hint.patch"
  pull_request:
    branches: [ main ]
    paths:
      - ".github/workflows/build-hint*dockerfile.yml"
      - ".github/workflows/build-dockerfile.yml"
      - "containers/hint*.Dockerfile"
      - "containers/patches/hint.patch"

jobs:
  build-hint-dockerfile:
    name: Build  HiNT Dockerfile
    uses: paulsengroup/2022-mcf10a-cancer-progression/.github/workflows/build-dockerfile.yml@main
    with:
      dockerfile-glob: "containers/hint*.Dockerfile"

    permissions:
      contents: read
      packages: write
