# Copyright (c) 2023 Roberto Rossini (roberros@uio.no)
# SPDX-License-Identifier: MIT

name: Build dcHiC Dockerfile

on:
  push:
    branches: [ main ]
    paths:
      - ".github/workflows/build-dchic*dockerfile.yml"
      - ".github/workflows/build-dockerfile.yml"
      - "containers/dchic*.Dockerfile"
      - "containers/assets/dchic*.tar.xz"
  pull_request:
    branches: [ main ]
    paths:
      - ".github/workflows/build-dchic*dockerfile.yml"
      - ".github/workflows/build-dockerfile.yml"
      - "containers/dchic*.Dockerfile"
      - "containers/assets/dchic*.tar.xz"

jobs:
  build-dchic-dockerfile:
    name: Build dcHiC Dockerfile
    uses: paulsengroup/2022-mcf10a-cancer-progression/.github/workflows/build-dockerfile.yml@main
    with:
      dockerfile-glob: "containers/dchic*.Dockerfile"

    permissions:
      contents: read
      packages: write
