# Copyright (c) 2023 Roberto Rossini (roberros@uio.no)
# SPDX-License-Identifier: MIT

name: Build HiCTrans Dockerfile

on:
  push:
    branches: [ main ]
    paths:
      - ".github/workflows/build-hictrans*dockerfile.yml"
      - ".github/workflows/build-dockerfile.yml"
      - "containers/hictrans*.Dockerfile"
  pull_request:
    branches: [ main ]
    paths:
      - ".github/workflows/build-hictrans*dockerfile.yml"
      - ".github/workflows/build-dockerfile.yml"
      - "containers/hictrans*.Dockerfile"

jobs:
  build-hictrans-dockerfile:
    name: Build HiCTrans Dockerfile
    uses: paulsengroup/2022-mcf10a-cancer-progression/.github/workflows/build-dockerfile.yml@main
    with:
      dockerfile-glob: "containers/hictrans*.Dockerfile"

    permissions:
      contents: read
      packages: write
